name: Generate and Publish Site

on:
  push:
    branches:
      - main
    paths:
      - '**.adoc'
      - 'src/docs/**'
      - 'docToolchainConfig.groovy'
      - 'README.md'
      - '.github/workflows/generate-site.yml'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Generate Site
        run: |
          ./dtcw docker generateSite

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: build/

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
